### ISSUE TITLE
Add BOM/part numbers

### ISSUE THREAD

**Issue by blalor** [Chromico/Raspberry-Pi-Screw-Terminal-Shield#1]
Can you please provide part numbers (or dimensions) for the board components? It looks like the through-hole spacing is 0.1" but it'd be nice to have that documented.

**Comment by Chromico** [comment]
Hey, 
Here is where you can get the components: 

**Screw terminal connectors**

https://lcsc.com/product-detail/Screw-terminal_Cixi-Kefa-Elec-KF128-2-54-10P_C474928.html

**Female pin header**

https://lcsc.com/product-detail/Female-Headers_BOOMELE-Boom-Precision-Elec-C50982_C50982.html

**Comment by Chromico** [comment]
Also, I didn't get what you meant by "through-hole spacing is 0.1"? Could you be a bit more specific about which footprint you're referring to?

**Comment by blalor** [comment]
Thank you! I was referring to the pitch, 2.54mm per the specs of the terminals you linked. 2.54mm ~= 0.1”. 😁
